# Generated by Django 5.1.5 on 2025-02-07 13:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='codigo',
            field=models.CharField(default='DEFAULT123', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='O código do produto deve conter apenas letras e números.', regex='^[a-zA-Z0-9]+$')]),
        ),
        migrations.AddField(
            model_name='produto',
            name='quantidade_estoque',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='A quantidade em estoque deve ser um número inteiro maior ou igual a zero.')]),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='O nome deve ter pelo menos 3 caracteres e não conter espaços especiais.', regex='^\\w{3,}$')]),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, message='O preço deve ser maior que zero.')]),
        ),
    ]
