# Generated by Django 5.1.5 on 2025-03-04 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0002_produto_codigo_produto_quantidade_estoque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produto/'),
        ),
    ]
